# 09 - Preprocesado de tags semanticos

Este notebook prepara tags semanticos limpios de MovieLens para el recomendador hibrido final. El enfoque no conserva un tag solo porque no este en una blacklist: primero aplica rechazos duros explicables, despues clasifica cada tag en categorias semanticas utiles y finalmente aplica filtros estadisticos de fiabilidad. El resultado se guarda en `data/processed/` para que el notebook 08 pueda reutilizarlo sin recalcular la limpieza pesada.

## 1. Imports y rutas

In [12]:
import math
import re
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings('default')

ROOT = Path('..')
DATA_RAW = ROOT / 'data' / 'raw'
DATA_PROCESSED = ROOT / 'data' / 'processed'
REPORTS_RESULTADOS = ROOT / 'reports' / 'resultados'

DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
REPORTS_RESULTADOS.mkdir(parents=True, exist_ok=True)

TAGS_PATH = DATA_RAW / 'tags.csv'
TAGS_SEMANTIC_CLEAN_PATH = DATA_PROCESSED / 'tags_semantic_clean.csv'
TAG_SEMANTIC_STATS_PATH = DATA_PROCESSED / 'tag_semantic_stats.csv'
TAG_BLACKLIST_DETECTED_PATH = DATA_PROCESSED / 'tag_blacklist_detected.csv'
TAG_BLACKLIST_MANUAL_PATH = DATA_PROCESSED / 'tag_blacklist_manual.csv'

## 2. Carga de tags.csv

In [13]:
if not TAGS_PATH.exists():
    raise FileNotFoundError('No existe data/raw/tags.csv. Descarga MovieLens completo y colocalo en data/raw/.')

tags_raw = pd.read_csv(TAGS_PATH)

print('Shape:', tags_raw.shape)
print('Columnas:', list(tags_raw.columns))
print('Peliculas distintas:', tags_raw['movieId'].nunique() if 'movieId' in tags_raw.columns else 'movieId no existe')
print('Usuarios distintos:', tags_raw['userId'].nunique() if 'userId' in tags_raw.columns else 'userId no existe')
print('Tags unicos brutos:', tags_raw['tag'].nunique(dropna=True) if 'tag' in tags_raw.columns else 'tag no existe')
print('Porcentaje de tags nulos:', round(tags_raw['tag'].isna().mean() * 100, 4) if 'tag' in tags_raw.columns else 'tag no existe')

Shape: (2000072, 4)
Columnas: ['userId', 'movieId', 'tag', 'timestamp']
Peliculas distintas: 51323
Usuarios distintos: 15848
Tags unicos brutos: 140979
Porcentaje de tags nulos: 0.0008

## 3. Reglas duras manuales

In [14]:
HARD_REJECTION_GROUPS = {
    'ownership_watch_status': [
        'owned', 'own', 'seen', 'watched', 'watchlist', 'want to see', 'to watch',
    ],
    'admin_platform': [
        'dvd', 'bd-r', 'bdr', 'blu-ray', 'bluray', 'blue-ray', 'vhs', 'netflix',
        'amazon', 'hulu', 'criterion', 'criterion collection', 'library', 'collection',
        'on dvr', 'recorded', 'tivo',
    ],
    'ranking_or_canon': [
        'imdb', 'imdb top 250', 'top 250', 'top 100', 'afi', 'afi 100',
        '1001 movies', '1001 movies you must see before you die', 'national film registry',
        'library of congress', 'sight and sound', 'sight & sound', 'must see',
        'classic', 'classics', 'cult classic', 'cult film',
    ],
    'award': [
        'oscar', 'oscars', 'oscar winner', 'oscar nominated', 'academy award',
        'academy awards', 'award winner', 'award nominated', 'best picture',
        'golden globe', "palme d'or", 'golden palm', 'cannes', 'film festival',
        'festival winner',
    ],
    'generic_rating': [
        'good', 'great', 'best', 'bad', 'worst', 'boring', 'funny', 'very funny',
        'hilarious', 'overrated', 'underrated', 'favorite', 'favourite', 'favorites',
        'favourites', 'excellent', 'amazing', 'awesome', 'terrible', 'awful',
        'mediocre', 'masterpiece', 'brilliant', 'great acting', 'good acting',
        'bad acting', 'acting', 'well acted', 'well-acted', 'entertaining',
        'inspirational', 'touching', 'beautiful', 'beautifully filmed', 'well made',
        'well-made', 'slow paced',
    ],
    'metadata_weak': [
        'movie', 'movies', 'film', 'films', 'cinema', 'cinematic', 'based on',
        'based on book', 'based on a book', 'based on true story',
        'based on a true story', 'based on real events', 'true story', 'adapted from',
        'adaptation', 'remake', 'sequel', 'franchise', 'original', 'foreign',
        'foreign language', 'television', 'tv movie', 'made for tv', 'miniseries',
    ],
    'pure_genre': [
        'drama', 'comedy', 'action', 'thriller', 'romance', 'horror', 'sci-fi',
        'science fiction', 'crime', 'adventure', 'animation', 'children', 'fantasy',
        'mystery', 'documentary', 'war', 'western', 'musical', 'film-noir',
        'film noir', 'noir',
    ],
    'format_or_source': [
        'nudity', 'nudity (full frontal)', 'full frontal nudity', 'sex', 'sexual content',
    ],
    'person_or_studio_manual': [
        'christopher nolan', 'coen brothers', 'coen brother', 'tom hanks',
        'hans zimmer', 'jack nicholson', 'robert downey jr.', 'jordan peele',
        'morgan freeman', 'sandra bullock', 'jesse eisenberg', 'leonardo dicaprio',
        'brad pitt', 'quentin tarantino', 'martin scorsese', 'steven spielberg',
        'david fincher', 'ridley scott', 'pixar', 'disney', 'walt disney',
        'marvel', 'dc', 'dc comics', 'warner bros', 'dreamworks', 'studio ghibli',
        'ghibli', 'lucasfilm', 'hbo', 'netflix original',
    ],
}

manual_blacklist = (
    pd.DataFrame(
        {'tag_clean': tag, 'reason': reason}
        for reason, tags in HARD_REJECTION_GROUPS.items()
        for tag in tags
    )
    .drop_duplicates('tag_clean')
    .sort_values(['reason', 'tag_clean'])
)
manual_blacklist.to_csv(TAG_BLACKLIST_MANUAL_PATH, index=False)

HARD_REJECTION_REASON_BY_TAG = dict(zip(manual_blacklist['tag_clean'], manual_blacklist['reason']))

print('Reglas duras manuales guardadas en:', TAG_BLACKLIST_MANUAL_PATH)
print('Tags exactos en reglas duras manuales:', len(manual_blacklist))
display(manual_blacklist.head(30))

Reglas duras manuales guardadas en: ..\data\processed\tag_blacklist_manual.csv
Tags exactos en reglas duras manuales: 175

               tag_clean          reason
15                amazon  admin_platform
8                   bd-r  admin_platform
9                    bdr  admin_platform
10               blu-ray  admin_platform
12              blue-ray  admin_platform
11                bluray  admin_platform
20            collection  admin_platform
17             criterion  admin_platform
18  criterion collection  admin_platform
7                    dvd  admin_platform
16                  hulu  admin_platform
19               library  admin_platform
14               netflix  admin_platform
21                on dvr  admin_platform
22              recorded  admin_platform
23                  tivo  admin_platform
13                   vhs  admin_platform
45         academy award           award
46        academy awards           award
48       award nominated           award
47          award winner           award
49          best picture           award
53                cannes           award
55       festival winner           award
54         film festival           award
50          golden globe           award
52           golden palm           award
41                 oscar           award
44       oscar nominated           award
43          oscar winner           award

## 4. Normalizacion, rechazos duros y NLP ligero

In [15]:
DASH_TRANSLATION = str.maketrans({
    '?': '-', '?': '-', '?': '-', '?': '-', '?': '-', '?': '-', '?': '-',
})

CONTAINS_REJECTION_PATTERNS = [
    ('http', 'url_or_web'),
    ('www.', 'url_or_web'),
    ('imdb', 'ranking_or_canon'),
    ('oscar', 'award'),
    ('academy award', 'award'),
    ('criterion', 'admin_platform'),
    ('netflix', 'admin_platform'),
    ('dvd', 'admin_platform'),
    ('blu', 'admin_platform'),
    ('owned', 'ownership_watch_status'),
    ('watchlist', 'ownership_watch_status'),
    ('want to see', 'ownership_watch_status'),
    ('seen', 'ownership_watch_status'),
    ('watched', 'ownership_watch_status'),
    ('top 250', 'ranking_or_canon'),
    ('1001 movies', 'ranking_or_canon'),
    ('national film registry', 'ranking_or_canon'),
    ('library of congress', 'ranking_or_canon'),
    ('film registry', 'ranking_or_canon'),
    ('sight and sound', 'ranking_or_canon'),
    ('sight & sound', 'ranking_or_canon'),
    ('award nominated', 'award'),
    ('award winner', 'award'),
    ('based on true', 'metadata_weak'),
    ('based on a true', 'metadata_weak'),
    ('foreign language', 'metadata_weak'),
    ('made for tv', 'metadata_weak'),
    ('full frontal', 'format_or_source'),
]

SEMANTIC_CATEGORY_PATTERNS = {
    'narrative_structure': [
        'plot twist', 'twist ending', 'twist', 'surprise ending', 'ambiguous ending',
        'open ending', 'ending', 'nonlinear', 'non-linear', 'narrated', 'narration',
        'voiceover', 'multiple storylines', 'parallel storylines', 'unreliable narrator',
        'time loop', 'time travel', 'flashback', 'dream sequence', 'confusing',
        'cerebral', 'mindfuck', 'puzzle', 'mystery', 'slow burn', 'paced',
        'character study', 'dialogue-driven', 'dialogue driven',
    ],
    'theme': [
        'artificial intelligence', 'ai', 'robot', 'robots', 'android', 'cyborg',
        'dystopia', 'dystopian', 'post-apocalyptic', 'apocalypse', 'space',
        'astronaut', 'alien', 'aliens', 'time travel', 'time loop', 'memory',
        'identity', 'existentialism', 'existential', 'morality', 'moral', 'ethics',
        'grief', 'loss', 'loneliness', 'alienation', 'obsession', 'revenge',
        'redemption', 'guilt', 'trauma', 'mental illness', 'psychology',
        'psychological', 'dreams', 'afterlife', 'death', 'religion', 'faith',
        'philosophy', 'philosophical', 'social commentary', 'class', 'capitalism',
        'political', 'politics', 'war trauma', 'coming of age', 'friendship',
        'family relationships', 'father', 'mother', 'childhood', 'racism', 'gender',
        'feminism', 'media', 'technology', 'virtual reality', 'magical realism',
    ],
    'humor': [
        'dark comedy', 'black comedy', 'satire', 'satirical', 'absurd comedy',
        'absurd', 'deadpan', 'parody', 'spoof', 'quirky', 'offbeat', 'screwball',
        'slapstick', 'dry humor', 'surreal humor', 'witty', 'ironic', 'irony',
    ],
    'visual_style': [
        'stylized', 'style', 'visual', 'visually', 'cinematography',
        'beautifully shot', 'photography', 'colorful', 'minimalist', 'experimental',
        'expressionist', 'dreamlike', 'surreal', 'surrealism', 'animation style',
        'stop motion', 'rotoscoping', 'neo-noir', 'black and white', 'b&w',
        'long take', 'long takes', 'single take', 'shaky camera', 'handheld',
        'slow motion', 'practical effects',
    ],
    'tone_atmosphere': [
        'atmospheric', 'atmosphere', 'moody', 'dark', 'bleak', 'tense', 'tension',
        'melancholic', 'melancholy', 'dreamlike', 'haunting', 'creepy', 'eerie',
        'disturbing', 'bittersweet', 'sad', 'depressing', 'somber', 'gritty',
        'grim', 'weird', 'strange', 'hypnotic', 'meditative', 'quiet', 'lonely',
        'alienating', 'claustrophobic', 'paranoid', 'nostalgic', 'hope', 'hopeful',
        'heartwarming', 'feel-good', 'whimsical', 'absurd', 'absurdism', 'surreal',
        'surrealism',
    ],
    'emotional_cognitive_experience': [
        'thought-provoking', 'thought provoking', 'mind-bending', 'mind bending',
        'cerebral', 'intellectual', 'philosophical', 'emotional', 'moving',
        'powerful', 'intense', 'absorbing', 'engrossing', 'immersive',
        'challenging', 'complex', 'ambiguous', 'provocative', 'unsettling',
        'memorable',
    ],
    'intensity_darkness': [
        'violent', 'violence', 'brutal', 'disturbing', 'gory', 'bloody', 'dark',
        'bleak', 'scary', 'creepy', 'horror atmosphere', 'tense', 'suspenseful',
        'suspense', 'tragic', 'tragedy', 'depressing', 'nihilistic', 'revenge',
        'murder', 'serial killer',
    ],
}
SEMANTIC_CATEGORY_PRIORITY = [
    'narrative_structure',
    'theme',
    'humor',
    'visual_style',
    'tone_atmosphere',
    'emotional_cognitive_experience',
    'intensity_darkness',
]

PERSON_NAME_PROTECTED_EXPRESSIONS = {
    'time travel', 'dark comedy', 'black comedy', 'social commentary',
    'artificial intelligence', 'twist ending', 'coming of age', 'great soundtrack',
    'soundtrack', 'surreal', 'dreamlike', 'psychological', 'dystopia',
    'atmospheric', 'existentialism', 'neo-noir', 'noir', 'ambiguous ending',
    'morality', 'revenge', 'memory', 'identity', 'grief', 'lonely', 'alienation',
}
PERSON_NAME_SEMANTIC_WORDS = {
    'time', 'travel', 'dark', 'comedy', 'black', 'social', 'commentary',
    'artificial', 'intelligence', 'twist', 'ending', 'coming', 'age',
    'soundtrack', 'surreal', 'dream', 'dreamlike', 'psychological', 'dystopia',
    'atmospheric', 'existentialism', 'neo-noir', 'noir', 'ambiguous', 'morality',
    'revenge', 'memory', 'identity', 'grief', 'lonely', 'alienation',
}


def normalize_tag_text(tag):
    tag_clean = str(tag).lower().strip().translate(DASH_TRANSLATION)
    tag_clean = tag_clean.replace('_', ' ')
    tag_clean = re.sub(r'\s+', ' ', tag_clean).strip()
    tag_clean = tag_clean.strip(' \t\n\r\"\'`?????')
    tag_clean = re.sub(r'\s+', ' ', tag_clean).strip()
    if not tag_clean or tag_clean in {'nan', 'none', 'null'}:
        return None
    return tag_clean


def _contains_keyword(tag_clean, keyword):
    if not tag_clean or not keyword:
        return False
    keyword = keyword.lower()
    if re.fullmatch(r'[a-z0-9]+', keyword):
        return re.search(rf'(?<![a-z0-9]){re.escape(keyword)}(?![a-z0-9])', tag_clean) is not None
    return keyword in tag_clean


def classify_hard_rejection(tag_clean, tag_original=None):
    if tag_clean is None or pd.isna(tag_clean) or not str(tag_clean).strip():
        return 'null_or_empty'
    tag_clean = str(tag_clean).strip()

    if len(tag_clean) < 2:
        return 'too_short'
    if re.fullmatch(r'(19\d{2}|20[0-2]\d)', tag_clean):
        year = int(tag_clean)
        if 1900 <= year <= 2029:
            return 'exact_year'
    if re.fullmatch(r'(19[5-9]0s|20[0-2]0s|[5-9]0s)', tag_clean):
        return 'decade'
    if re.fullmatch(r'\d+(?:\.\d+)?', tag_clean):
        return 'numeric'
    if re.fullmatch(r'[\W_]+', tag_clean):
        return 'punctuation_only'

    exact_reason = HARD_REJECTION_REASON_BY_TAG.get(tag_clean)
    if exact_reason is not None:
        return exact_reason

    for pattern, reason in CONTAINS_REJECTION_PATTERNS:
        if pattern in tag_clean:
            return reason

    return None


def detect_semantic_category(tag_clean):
    if tag_clean is None or pd.isna(tag_clean):
        return None
    tag_clean = str(tag_clean).strip()
    for category in SEMANTIC_CATEGORY_PRIORITY:
        if any(_contains_keyword(tag_clean, keyword) for keyword in SEMANTIC_CATEGORY_PATTERNS[category]):
            return category
    return None


def detect_semantic_match_reason(tag_clean, semantic_category):
    """
    Devuelve el patron semantico que hizo coincidir un tag con su categoria.
    Si el tag no tiene categoria semantica util, devuelve None.

    Pandas puede convertir None en NaN dentro de semantic_category, asi que
    hay que controlar explicitamente los valores nulos.
    """
    if tag_clean is None or pd.isna(tag_clean):
        return None

    if semantic_category is None or pd.isna(semantic_category):
        return None

    tag_clean = str(tag_clean).strip().lower()
    semantic_category = str(semantic_category).strip()

    if not tag_clean:
        return None

    if semantic_category not in SEMANTIC_CATEGORY_PATTERNS:
        return None

    for keyword in SEMANTIC_CATEGORY_PATTERNS.get(semantic_category, []):
        if _contains_keyword(tag_clean, keyword):
            return keyword

    return None


def looks_like_person_name(tag_original, tag_clean):
    if tag_clean is None or tag_clean in PERSON_NAME_PROTECTED_EXPRESSIONS:
        return False
    if any(word in tag_clean.split() for word in PERSON_NAME_SEMANTIC_WORDS):
        return False

    original = str(tag_original).strip().translate(DASH_TRANSLATION)
    tokens = [token.strip('.,:;!?()[]{}\"\'`?????') for token in original.split()]
    tokens = [token for token in tokens if token]
    if len(tokens) not in {2, 3}:
        return False

    capitalized_tokens = sum(bool(re.match(r'^[A-Z??????][A-Za-z????????????\'-]+$', token)) for token in tokens)
    return capitalized_tokens >= 2

## 5. Crear tags normalizados y categorias semanticas

In [16]:
tags_work = tags_raw.copy()
tags_work['tag_original'] = tags_work['tag'].astype(str)
tags_work['tag_clean'] = tags_work['tag'].apply(normalize_tag_text)
tags_work['hard_rejection_reason'] = tags_work.apply(
    lambda row: classify_hard_rejection(row['tag_clean'], row['tag_original']), axis=1
)
tags_work['semantic_category'] = tags_work['tag_clean'].apply(detect_semantic_category)
tags_work['semantic_match_reason'] = tags_work.apply(
    lambda row: detect_semantic_match_reason(row['tag_clean'], row['semantic_category']), axis=1
)

print("Tags con categoria semantica util:", tags_work['semantic_category'].notna().sum())
print("Tags sin categoria semantica:", tags_work['semantic_category'].isna().sum())
display(tags_work['semantic_category'].value_counts(dropna=False))

tags_work['person_name_like'] = tags_work.apply(
    lambda row: (
        pd.isna(row['hard_rejection_reason'])
        and pd.isna(row['semantic_category'])
        and looks_like_person_name(row['tag_original'], row['tag_clean'])
    ),
    axis=1,
)
tags_work['semantic_rejection_reason'] = np.select(
    [tags_work['person_name_like'], tags_work['semantic_category'].isna()],
    ['person_name_like', 'semantic_category_missing'],
    default=None,
)
tags_work.loc[tags_work['hard_rejection_reason'].notna(), 'semantic_rejection_reason'] = None

tags_work['preliminary_keep'] = tags_work['hard_rejection_reason'].isna() & tags_work['semantic_category'].notna()
tags_work_nonnull = tags_work[tags_work['tag_clean'].notna()].copy()

dedup_cols = ['movieId', 'tag_clean']
if 'userId' in tags_work_nonnull.columns:
    dedup_cols = ['userId', 'movieId', 'tag_clean']

tags_work_dedup = tags_work_nonnull.drop_duplicates(dedup_cols).copy()
preliminary_tags = tags_work_dedup[tags_work_dedup['preliminary_keep']].copy()

print('Filas originales:', len(tags_raw))
print('Tags unicos brutos:', tags_raw['tag'].nunique(dropna=True))
print('Filas con tag_clean valido:', len(tags_work_nonnull))
print('Filas deduplicadas con tag_clean valido:', len(tags_work_dedup))
print('Tags preliminares con semantic_category util:', preliminary_tags['tag_clean'].nunique())
print('Filas preliminares:', len(preliminary_tags))

Tags con categoria semantica util: 333937
Tags sin categoria semantica: 1666135

semantic_category
NaN                               1666135
theme                              123926
tone_atmosphere                     46275
narrative_structure                 45901
visual_style                        44031
intensity_darkness                  30322
humor                               28819
emotional_cognitive_experience      14663
Name: count, dtype: int64

Filas originales: 2000072
Tags unicos brutos: 140979
Filas con tag_clean valido: 2000049
Filas deduplicadas con tag_clean valido: 1999997
Tags preliminares con semantic_category util: 6115
Filas preliminares: 328367

## 6. Estadisticas globales y fiabilidad

In [17]:
def mode_or_first(values):
    values = values.dropna()
    if values.empty:
        return None
    mode = values.mode()
    return mode.iloc[0] if not mode.empty else values.iloc[0]


def build_tag_usage_stats(df, n_movies_total_with_tags):
    stats = df.groupby('tag_clean', as_index=False).agg(
        n_uses=('tag_clean', 'size'),
        n_movies=('movieId', 'nunique'),
    )
    if 'userId' in df.columns:
        user_stats = df.groupby('tag_clean', as_index=False).agg(n_users=('userId', 'nunique'))
        top_user_stats = (
            df.groupby(['tag_clean', 'userId'])
            .size()
            .groupby('tag_clean')
            .max()
            .rename('top_user_uses')
            .reset_index()
        )
        stats = stats.merge(user_stats, on='tag_clean', how='left').merge(top_user_stats, on='tag_clean', how='left')
    else:
        stats['n_users'] = np.nan
        stats['top_user_uses'] = np.nan

    stats['top_user_share'] = stats['top_user_uses'] / stats['n_uses']
    stats['pct_movies'] = stats['n_movies'] / max(n_movies_total_with_tags, 1)
    stats['idf'] = np.log((1 + n_movies_total_with_tags) / (1 + stats['n_movies'])) + 1
    return stats


def first_statistical_rejection(row):
    if not row['preliminary_keep'] or row['passes_statistical_filters']:
        return None
    if row['fail_low_n_movies']:
        return 'low_n_movies'
    if row['fail_low_n_users']:
        return 'low_n_users'
    if row['fail_high_pct_movies']:
        return 'high_pct_movies'
    if row['fail_high_top_user_share']:
        return 'high_top_user_share'
    return None

n_movies_total_with_tags = preliminary_tags['movieId'].nunique()
base_stats = build_tag_usage_stats(tags_work_dedup, n_movies_total_with_tags)

tag_attributes = tags_work_dedup.groupby('tag_clean').agg(
    semantic_category=('semantic_category', mode_or_first),
    semantic_match_reason=('semantic_match_reason', mode_or_first),
    preliminary_keep=('preliminary_keep', 'max'),
    hard_rejection_reason=('hard_rejection_reason', mode_or_first),
    semantic_rejection_reason=('semantic_rejection_reason', mode_or_first),
).reset_index()

tag_stats = base_stats.merge(tag_attributes, on='tag_clean', how='left')
tag_stats['preliminary_keep'] = tag_stats['preliminary_keep'].fillna(False).astype(bool)
tag_stats['fail_low_n_movies'] = tag_stats['n_movies'] < 5
tag_stats['fail_low_n_users'] = tag_stats['n_users'] < 5 if 'userId' in tags_work_dedup.columns else False
tag_stats['fail_high_pct_movies'] = tag_stats['pct_movies'] > 0.05
tag_stats['fail_high_top_user_share'] = tag_stats['top_user_share'] > 0.60 if 'userId' in tags_work_dedup.columns else False

tag_stats['passes_statistical_filters'] = (
    tag_stats['preliminary_keep']
    & ~tag_stats['fail_low_n_movies']
    & ~tag_stats['fail_low_n_users']
    & ~tag_stats['fail_high_pct_movies']
    & ~tag_stats['fail_high_top_user_share']
)
tag_stats['is_reliable_tag'] = tag_stats['preliminary_keep'] & tag_stats['passes_statistical_filters']
tag_stats['rejection_reason_statistical'] = tag_stats.apply(first_statistical_rejection, axis=1)

reliable_tag_stats = tag_stats[tag_stats['is_reliable_tag']].copy()

print('Tags aceptados antes de fiabilidad:', int(tag_stats['preliminary_keep'].sum()))
print('Tags finales fiables:', len(reliable_tag_stats))
print('Eliminados por low_n_movies:', int((tag_stats['preliminary_keep'] & tag_stats['fail_low_n_movies']).sum()))
print('Eliminados por low_n_users:', int((tag_stats['preliminary_keep'] & tag_stats['fail_low_n_users']).sum()))
print('Eliminados por high_pct_movies:', int((tag_stats['preliminary_keep'] & tag_stats['fail_high_pct_movies']).sum()))
print('Eliminados por high_top_user_share:', int((tag_stats['preliminary_keep'] & tag_stats['fail_high_top_user_share']).sum()))

display(reliable_tag_stats.sort_values('n_uses', ascending=False).head(30))
display(reliable_tag_stats.sort_values('n_movies', ascending=False).head(30))

Tags aceptados antes de fiabilidad: 6115
Tags finales fiables: 534
Eliminados por low_n_movies: 4778
Eliminados por low_n_users: 5158
Eliminados por high_pct_movies: 7
Eliminados por high_top_user_share: 4700

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
7469,atmospheric,10088,817,2205,213,0.021114,0.037940,4.270572,tone_atmosphere,atmospheric,True,NaN,NaN,False,False,False,False,True,True,NaN
113594,surreal,7480,688,2080,84,0.011230,0.031949,4.442194,visual_style,surreal,True,NaN,NaN,False,False,False,False,True,True,NaN
124585,visually appealing,7253,481,2092,54,0.007445,0.022337,4.799491,visual_style,visually,True,NaN,NaN,False,False,False,False,True,True,NaN
121175,twist ending,6600,386,2088,54,0.008182,0.017925,5.019010,narrative_structure,twist ending,True,NaN,NaN,False,False,False,False,True,True,NaN
27909,dark comedy,6153,742,1958,386,0.062734,0.034457,4.366739,humor,dark comedy,True,NaN,NaN,False,False,False,False,True,True,NaN
117306,thought-provoking,6003,360,2035,65,0.010828,0.016718,5.088557,emotional_cognitive_experience,thought-provoking,True,NaN,NaN,False,False,False,False,True,True,NaN
33985,dystopia,5713,441,1568,338,0.059163,0.020479,4.886125,theme,dystopia,True,NaN,NaN,False,False,False,False,True,True,NaN
21945,cinematography,5429,757,1513,85,0.015657,0.035154,4.346751,visual_style,cinematography,True,NaN,NaN,False,False,False,False,True,True,NaN
108136,social commentary,5201,692,1529,160,0.030763,0.032135,4.436405,theme,social commentary,True,NaN,NaN,False,False,False,False,True,True,NaN
88467,quirky,4954,515,1459,141,0.028462,0.023916,4.731328,humor,quirky,True,NaN,NaN,False,False,False,False,True,True,NaN
112643,stylized,4948,485,1370,200,0.040420,0.022523,4.791226,visual_style,stylized,True,NaN,NaN,False,False,False,False,True,True,NaN
87569,psychology,4847,326,1675,65,0.013410,0.015139,5.187475,theme,psychology,True,NaN,NaN,False,False,False,False,True,True,NaN
27896,dark,4825,522,1527,56,0.011606,0.024241,4.717853,tone_atmosphere,dark,True,NaN,NaN,False,False,False,False,True,True,NaN
118038,time travel,4740,578,1504,486,0.102532,0.026841,4.616132,narrative_structure,time travel,True,NaN,NaN,False,False,False,False,True,True,NaN
23905,coming of age,4494,1029,1133,439,0.097686,0.047785,4.040121,theme,coming of age,True,NaN,NaN,False,False,False,False,True,True,NaN
87535,psychological,4081,353,1483,52,0.012742,0.016393,5.108138,theme,psychological,True,NaN,NaN,False,False,False,False,True,True,NaN
12519,black comedy,4071,739,1345,475,0.116679,0.034318,4.370785,humor,black comedy,True,NaN,NaN,False,False,False,False,True,True,NaN
31619,disturbing,4053,430,1343,116,0.028621,0.019968,4.911327,tone_atmosphere,disturbing,True,NaN,NaN,False,False,False,False,True,True,NaN
109097,space,3971,306,1376,127,0.031982,0.014210,5.250587,theme,space,True,NaN,NaN,False,False,False,False,True,True,NaN
3668,aliens,3642,391,976,141,0.038715,0.018157,5.006173,theme,aliens,True,NaN,NaN,False,False,False,False,True,True,NaN
100840,satire,3573,764,1229,450,0.125945,0.035479,4.337559,humor,satire,True,NaN,NaN,False,False,False,False,True,True,NaN
71355,mindfuck,3457,178,1385,51,0.014753,0.008266,5.790049,narrative_structure,mindfuck,True,NaN,NaN,False,False,False,False,True,True,NaN
85701,post-apocalyptic,2881,279,1062,170,0.059007,0.012956,5.342645,theme,post-apocalyptic,True,NaN,NaN,False,False,False,False,True,True,NaN
103370,serial killer,2763,785,828,523,0.189287,0.036454,4.310478,intensity_darkness,serial killer,True,NaN,NaN,False,False,False,False,True,True,NaN
32921,dreamlike,2759,225,1071,58,0.021022,0.010449,5.556900,visual_style,dreamlike,True,NaN,NaN,False,False,False,False,True,True,NaN
12411,bittersweet,2757,270,1065,66,0.023939,0.012538,5.375316,tone_atmosphere,bittersweet,True,NaN,NaN,False,False,False,False,True,True,NaN
70118,mental illness,2698,578,942,208,0.077094,0.026841,4.616132,theme,mental illness,True,NaN,NaN,False,False,False,False,True,True,NaN
6917,artificial intelligence,2652,184,1096,128,0.048265,0.008545,5.757079,theme,artificial intelligence,True,NaN,NaN,False,False,False,False,True,True,NaN
115943,tense,2643,415,948,185,0.069996,0.019272,4.946750,tone_atmosphere,tense,True,NaN,NaN,False,False,False,False,True,True,NaN
85006,politics,2416,836,718,427,0.176738,0.038822,4.247611,theme,politics,True,NaN,NaN,False,False,False,False,True,True,NaN

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
23905,coming of age,4494,1029,1133,439,0.097686,0.047785,4.040121,theme,coming of age,True,NaN,NaN,False,False,False,False,True,True,NaN
39297,father daughter relationship,1517,974,287,767,0.505603,0.045231,4.094997,theme,father,True,NaN,NaN,False,False,False,False,True,True,NaN
38823,family relationships,1305,925,245,702,0.537931,0.042955,4.146561,theme,family relationships,True,NaN,NaN,False,False,False,False,True,True,NaN
85006,politics,2416,836,718,427,0.176738,0.038822,4.247611,theme,politics,True,NaN,NaN,False,False,False,False,True,True,NaN
7469,atmospheric,10088,817,2205,213,0.021114,0.037940,4.270572,tone_atmosphere,atmospheric,True,NaN,NaN,False,False,False,False,True,True,NaN
103370,serial killer,2763,785,828,523,0.189287,0.036454,4.310478,intensity_darkness,serial killer,True,NaN,NaN,False,False,False,False,True,True,NaN
96494,religion,2163,776,651,346,0.159963,0.036036,4.321994,theme,religion,True,NaN,NaN,False,False,False,False,True,True,NaN
113611,surrealism,1752,774,602,707,0.403539,0.035943,4.324572,visual_style,surrealism,True,NaN,NaN,False,False,False,False,True,True,NaN
100840,satire,3573,764,1229,450,0.125945,0.035479,4.337559,humor,satire,True,NaN,NaN,False,False,False,False,True,True,NaN
21945,cinematography,5429,757,1513,85,0.015657,0.035154,4.346751,visual_style,cinematography,True,NaN,NaN,False,False,False,False,True,True,NaN
27909,dark comedy,6153,742,1958,386,0.062734,0.034457,4.366739,humor,dark comedy,True,NaN,NaN,False,False,False,False,True,True,NaN
113564,surprise ending,1379,739,435,667,0.483684,0.034318,4.370785,narrative_structure,surprise ending,True,NaN,NaN,False,False,False,False,True,True,NaN
12519,black comedy,4071,739,1345,475,0.116679,0.034318,4.370785,humor,black comedy,True,NaN,NaN,False,False,False,False,True,True,NaN
108136,social commentary,5201,692,1529,160,0.030763,0.032135,4.436405,theme,social commentary,True,NaN,NaN,False,False,False,False,True,True,NaN
113594,surreal,7480,688,2080,84,0.011230,0.031949,4.442194,visual_style,surreal,True,NaN,NaN,False,False,False,False,True,True,NaN
70118,mental illness,2698,578,942,208,0.077094,0.026841,4.616132,theme,mental illness,True,NaN,NaN,False,False,False,False,True,True,NaN
118038,time travel,4740,578,1504,486,0.102532,0.026841,4.616132,narrative_structure,time travel,True,NaN,NaN,False,False,False,False,True,True,NaN
88807,racism,1718,576,577,303,0.176368,0.026748,4.619593,theme,racism,True,NaN,NaN,False,False,False,False,True,True,NaN
12455,black and white,1940,554,605,112,0.057732,0.025727,4.658467,visual_style,black and white,True,NaN,NaN,False,False,False,False,True,True,NaN
27896,dark,4825,522,1527,56,0.011606,0.024241,4.717853,tone_atmosphere,dark,True,NaN,NaN,False,False,False,False,True,True,NaN
88467,quirky,4954,515,1459,141,0.028462,0.023916,4.731328,humor,quirky,True,NaN,NaN,False,False,False,False,True,True,NaN
3526,alien,992,488,229,455,0.458669,0.022662,4.785072,theme,alien,True,NaN,NaN,False,False,False,False,True,True,NaN
112643,stylized,4948,485,1370,200,0.040420,0.022523,4.791226,visual_style,stylized,True,NaN,NaN,False,False,False,False,True,True,NaN
124585,visually appealing,7253,481,2092,54,0.007445,0.022337,4.799491,visual_style,visually,True,NaN,NaN,False,False,False,False,True,True,NaN
78241,obsession,946,468,329,339,0.358351,0.021733,4.826832,theme,obsession,True,NaN,NaN,False,False,False,False,True,True,NaN
33985,dystopia,5713,441,1568,338,0.059163,0.020479,4.886125,theme,dystopia,True,NaN,NaN,False,False,False,False,True,True,NaN
31619,disturbing,4053,430,1343,116,0.028621,0.019968,4.911327,tone_atmosphere,disturbing,True,NaN,NaN,False,False,False,False,True,True,NaN
90299,redemption,814,416,289,250,0.307125,0.019318,4.944349,theme,redemption,True,NaN,NaN,False,False,False,False,True,True,NaN
115943,tense,2643,415,948,185,0.069996,0.019272,4.946750,tone_atmosphere,tense,True,NaN,NaN,False,False,False,False,True,True,NaN
81304,parody,2006,407,723,177,0.088235,0.018900,4.966168,humor,parody,True,NaN,NaN,False,False,False,False,True,True,NaN

## 7. Crear tag_semantic_stats.csv

In [18]:
TAG_STATS_COLUMNS = [
    'tag_clean',
    'semantic_category',
    'semantic_match_reason',
    'n_uses',
    'n_movies',
    'n_users',
    'top_user_uses',
    'top_user_share',
    'pct_movies',
    'idf',
    'passes_statistical_filters',
    'is_reliable_tag',
    'hard_rejection_reason',
    'semantic_rejection_reason',
    'rejection_reason_statistical',
]

tag_stats_export = tag_stats[TAG_STATS_COLUMNS].sort_values(
    ['is_reliable_tag', 'semantic_category', 'n_movies', 'n_uses'],
    ascending=[False, True, False, False],
)
tag_stats_export.to_csv(TAG_SEMANTIC_STATS_PATH, index=False)

print('Estadisticas guardadas en:', TAG_SEMANTIC_STATS_PATH)
print('Filas:', len(tag_stats_export))

Estadisticas guardadas en: ..\data\processed\tag_semantic_stats.csv
Filas: 131583

## 8. Crear tags_semantic_clean.csv

In [19]:
reliable_tag_details = tag_stats.loc[
    tag_stats['is_reliable_tag'],
    ['tag_clean', 'semantic_category', 'idf', 'n_uses', 'n_movies', 'n_users', 'top_user_share'],
].copy()

tags_semantic_clean = (
    preliminary_tags[['movieId', 'tag_clean']]
    .drop_duplicates(['movieId', 'tag_clean'])
    .merge(reliable_tag_details, on='tag_clean', how='inner')
    .sort_values(['movieId', 'tag_clean'])
)

tags_semantic_clean.to_csv(TAGS_SEMANTIC_CLEAN_PATH, index=False)

print('Tags semanticos limpios guardados en:', TAGS_SEMANTIC_CLEAN_PATH)
print('Filas finales tags_semantic_clean:', len(tags_semantic_clean))
print('Tags unicos finales:', tags_semantic_clean['tag_clean'].nunique())
print('Peliculas con tags semanticos limpios:', tags_semantic_clean['movieId'].nunique())

Tags semanticos limpios guardados en: ..\data\processed\tags_semantic_clean.csv
Filas finales tags_semantic_clean: 50897
Tags unicos finales: 534
Peliculas con tags semanticos limpios: 16795

## 9. Crear tag_blacklist_detected.csv

In [20]:
BLACKLIST_STATS_COLUMNS = [
    'tag_clean', 'semantic_category', 'n_uses', 'n_movies', 'n_users',
    'top_user_share', 'pct_movies', 'idf',
]

hard_detected = tag_stats[tag_stats['hard_rejection_reason'].notna()][BLACKLIST_STATS_COLUMNS + ['hard_rejection_reason']].copy()
hard_detected['rejection_source'] = 'hard_rules'
hard_detected = hard_detected.rename(columns={'hard_rejection_reason': 'rejection_reason'})

semantic_detected = tag_stats[
    tag_stats['hard_rejection_reason'].isna()
    & tag_stats['semantic_rejection_reason'].notna()
][BLACKLIST_STATS_COLUMNS + ['semantic_rejection_reason']].copy()
semantic_detected['rejection_source'] = 'semantic_rules'
semantic_detected = semantic_detected.rename(columns={'semantic_rejection_reason': 'rejection_reason'})

statistical_detected = tag_stats[
    tag_stats['rejection_reason_statistical'].notna()
][BLACKLIST_STATS_COLUMNS + ['rejection_reason_statistical']].copy()
statistical_detected['rejection_source'] = 'statistical_rules'
statistical_detected = statistical_detected.rename(columns={'rejection_reason_statistical': 'rejection_reason'})

tag_blacklist_detected = pd.concat([hard_detected, semantic_detected, statistical_detected], ignore_index=True)
tag_blacklist_detected = tag_blacklist_detected[
    ['tag_clean', 'rejection_source', 'rejection_reason', 'semantic_category', 'n_uses',
     'n_movies', 'n_users', 'top_user_share', 'pct_movies', 'idf']
].sort_values(['rejection_source', 'rejection_reason', 'n_movies', 'n_uses'], ascending=[True, True, False, False])

tag_blacklist_detected.to_csv(TAG_BLACKLIST_DETECTED_PATH, index=False)

print('Blacklist detectada guardada en:', TAG_BLACKLIST_DETECTED_PATH)
print('Filas:', len(tag_blacklist_detected))
display(tag_blacklist_detected.head(30))

Blacklist detectada guardada en: ..\data\processed\tag_blacklist_detected.csv
Filas: 131049

,tag_clean,rejection_source,rejection_reason,semantic_category,n_uses,n_movies,n_users,top_user_share,pct_movies,idf
204,bd-r,hard_rules,admin_platform,NaN,3967,3948,12,0.995210,0.183338,2.696217
356,criterion,hard_rules,admin_platform,NaN,2415,1450,221,0.589648,0.067335,3.697427
402,dvd-video,hard_rules,admin_platform,NaN,965,953,10,0.987565,0.044256,4.116771
968,tumey's dvds,hard_rules,admin_platform,NaN,649,640,7,0.986133,0.029720,4.514405
401,dvd-ram,hard_rules,admin_platform,NaN,560,556,5,0.992857,0.025820,4.654870
521,library,hard_rules,admin_platform,NaN,515,479,38,0.631068,0.022244,4.803649
558,netflix,hard_rules,admin_platform,NaN,586,464,135,0.244027,0.021547,4.835397
396,dvd,hard_rules,admin_platform,NaN,427,362,32,0.213115,0.016811,5.083032
224,blu-ray,hard_rules,admin_platform,NaN,335,333,3,0.991045,0.015464,5.166294
980,vhs,hard_rules,admin_platform,NaN,358,330,26,0.516760,0.015325,5.175316
400,dvd-r,hard_rules,admin_platform,NaN,333,327,9,0.900901,0.015185,5.184421
504,in netflix queue,hard_rules,admin_platform,NaN,345,319,24,0.472464,0.014814,5.209114
599,on dvr,hard_rules,admin_platform,NaN,282,280,4,0.939716,0.013003,5.339080
560,netflix finland,hard_rules,admin_platform,NaN,294,270,4,0.670068,0.012538,5.375316
960,tivo,hard_rules,admin_platform,NaN,168,168,2,0.994048,0.007802,5.847536
408,eric's dvds,hard_rules,admin_platform,NaN,162,160,3,0.987654,0.007430,5.896030
570,netflix streaming,hard_rules,admin_platform,NaN,117,104,27,0.333333,0.004830,6.323474
494,hulu,hard_rules,admin_platform,NaN,88,82,13,0.511364,0.003808,6.558594
586,not available from netflix,hard_rules,admin_platform,NaN,88,80,15,0.818182,0.003715,6.582986
552,my dvds,hard_rules,admin_platform,NaN,69,60,10,0.739130,0.002786,6.866561
509,j netflix,hard_rules,admin_platform,NaN,60,60,1,1.000000,0.002786,6.866561
183,amazon,hard_rules,admin_platform,NaN,90,54,40,0.422222,0.002508,6.970102
228,blue,hard_rules,admin_platform,NaN,51,48,7,0.725490,0.002229,7.085614
589,not on dvd,hard_rules,admin_platform,NaN,48,46,4,0.916667,0.002136,7.127287
298,blues,hard_rules,admin_platform,NaN,58,31,29,0.310345,0.001440,7.511699
227,bludgeoning,hard_rules,admin_platform,NaN,28,27,2,0.964286,0.001254,7.645230
406,emily blunt,hard_rules,admin_platform,NaN,303,25,202,0.019802,0.001161,7.719338
269,blue panties,hard_rules,admin_platform,NaN,24,23,2,0.958333,0.001068,7.799381
512,jeff goldblum,hard_rules,admin_platform,NaN,217,22,145,0.027650,0.001022,7.841941
1020,who cares dvds,hard_rules,admin_platform,NaN,23,22,2,0.956522,0.001022,7.841941

## 10. Diagnostico final

In [21]:
def safe_sample(df, n=50, random_state=42):
    if df.empty:
        return df
    return df.sample(min(n, len(df)), random_state=random_state)

print('Resumen')
print('Filas originales:', len(tags_raw))
print('Tags unicos brutos:', tags_raw['tag'].nunique(dropna=True))
print('Tags con tag_clean valido:', tags_work_nonnull['tag_clean'].nunique())
print('Tags preliminares con semantic_category util:', preliminary_tags['tag_clean'].nunique())
print('Tags finales fiables:', reliable_tag_stats['tag_clean'].nunique())
print('Filas finales en tags_semantic_clean:', len(tags_semantic_clean))
print('Peliculas con tags semanticos limpios:', tags_semantic_clean['movieId'].nunique())

print('\nDistribucion de semantic_category por tags unicos finales')
display(reliable_tag_stats['semantic_category'].value_counts(dropna=False).rename_axis('semantic_category').reset_index(name='n_tags'))

print('\nDistribucion de semantic_category por filas finales')
display(tags_semantic_clean['semantic_category'].value_counts(dropna=False).rename_axis('semantic_category').reset_index(name='n_rows'))

print('\nRechazos duros')
display(tags_work_dedup['hard_rejection_reason'].value_counts(dropna=False).rename_axis('hard_rejection_reason').reset_index(name='n_rows'))

semantic_missing_tags = tag_stats[tag_stats['semantic_rejection_reason'] == 'semantic_category_missing']
person_like_tags = tag_stats[tag_stats['semantic_rejection_reason'] == 'person_name_like']
print('Tags con semantic_category_missing:', len(semantic_missing_tags))
print('Tags rechazados por person_name_like:', len(person_like_tags))
print('Tags rechazados por low_n_movies:', int((tag_stats['preliminary_keep'] & tag_stats['fail_low_n_movies']).sum()))
print('Tags rechazados por low_n_users:', int((tag_stats['preliminary_keep'] & tag_stats['fail_low_n_users']).sum()))
print('Tags rechazados por high_pct_movies:', int((tag_stats['preliminary_keep'] & tag_stats['fail_high_pct_movies']).sum()))
print('Tags rechazados por high_top_user_share:', int((tag_stats['preliminary_keep'] & tag_stats['fail_high_top_user_share']).sum()))

for category in SEMANTIC_CATEGORY_PRIORITY:
    category_tags = reliable_tag_stats[reliable_tag_stats['semantic_category'] == category]
    if category_tags.empty:
        continue
    print(f'\nTop 20 tags finales por categoria: {category}')
    display(category_tags.sort_values(['n_movies', 'n_uses'], ascending=False).head(20))

print('\nMuestra aleatoria de 50 tags finales aceptados')
display(safe_sample(reliable_tag_stats[['tag_clean', 'semantic_category', 'n_movies', 'n_uses']], 50).sort_values('tag_clean'))

print('\nMuestra aleatoria de 50 tags rechazados por semantic_category_missing')
display(safe_sample(semantic_missing_tags[['tag_clean', 'n_movies', 'n_uses']], 50).sort_values('tag_clean'))

print('\nMuestra aleatoria de 50 tags rechazados por person_name_like')
display(safe_sample(person_like_tags[['tag_clean', 'n_movies', 'n_uses']], 50).sort_values('tag_clean'))

problematic_tags = [
    'national film registry', 'pixar', 'disney', 'brilliant', 'foreign',
    'based on a true story', '1980s', '1990s', 'nudity (full frontal)',
    'dave franco', 'isla fisher', 'christopher nolan', 'coen brothers',
    'tom hanks', 'hans zimmer', 'great acting', 'cult film', 'owned',
    'imdb top 250', 'oscar', 'criterion', 'dvd', 'netflix',
]
final_tag_set = set(tags_semantic_clean['tag_clean'])
problematic_check = pd.DataFrame({
    'tag_clean': problematic_tags,
    'present_in_tags_semantic_clean': [tag in final_tag_set for tag in problematic_tags],
})
print('\nComprobacion de tags problematicos')
display(problematic_check)

useful_tags = [
    'surrealism', 'dreamlike', 'existentialism', 'psychological',
    'ambiguous ending', 'neo-noir', 'atmospheric', 'time travel',
    'thought-provoking', 'dark comedy', 'black comedy', 'social commentary',
    'plot twist', 'twist ending', 'mindfuck', 'bittersweet', 'quirky',
    'satirical', 'cerebral', 'magical realism', 'tense', 'morality',
]
raw_tag_set = set(tags_work_nonnull['tag_clean'])
useful_check = pd.DataFrame({
    'tag_clean': useful_tags,
    'exists_in_tags_csv': [tag in raw_tag_set for tag in useful_tags],
    'present_in_tags_semantic_clean': [tag in final_tag_set for tag in useful_tags],
})
print('\nComprobacion de tags utiles')
display(useful_check)

existing_useful = useful_check[useful_check['exists_in_tags_csv']]
if len(existing_useful) and existing_useful['present_in_tags_semantic_clean'].mean() < 0.35:
    warnings.warn('Muchos tags utiles existentes quedaron fuera; revisa patrones o filtros estadisticos.')

Resumen
Filas originales: 2000072
Tags unicos brutos: 140979
Tags con tag_clean valido: 131583
Tags preliminares con semantic_category util: 6115
Tags finales fiables: 534
Filas finales en tags_semantic_clean: 50897
Peliculas con tags semanticos limpios: 16795

Distribucion de semantic_category por tags unicos finales

                semantic_category  n_tags
0                           theme     229
1             narrative_structure      90
2                 tone_atmosphere      60
3                    visual_style      46
4              intensity_darkness      45
5  emotional_cognitive_experience      35
6                           humor      29

Distribucion de semantic_category por filas finales

                semantic_category  n_rows
0                           theme   21939
1                 tone_atmosphere    7071
2             narrative_structure    6075
3                    visual_style    6021
4                           humor    5019
5              intensity_darkness    2958
6  emotional_cognitive_experience    1814

Rechazos duros

      hard_rejection_reason   n_rows
0                       NaN  1782686
1                pure_genre    84467
2            generic_rating    31678
3             metadata_weak    24592
4   person_or_studio_manual    21964
5            admin_platform    14377
6          ranking_or_canon    13349
7                     award     8697
8          format_or_source     6171
9                    decade     5990
10   ownership_watch_status     4064
11                too_short     1011
12                  numeric      470
13               exact_year      420
14         punctuation_only       35
15               url_or_web       26

Tags con semantic_category_missing: 111946
Tags rechazados por person_name_like: 12481
Tags rechazados por low_n_movies: 4778
Tags rechazados por low_n_users: 5158
Tags rechazados por high_pct_movies: 7
Tags rechazados por high_top_user_share: 4700

Top 20 tags finales por categoria: narrative_structure

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
113564,surprise ending,1379,739,435,667,0.483684,0.034318,4.370785,narrative_structure,surprise ending,True,NaN,NaN,False,False,False,False,True,True,NaN
118038,time travel,4740,578,1504,486,0.102532,0.026841,4.616132,narrative_structure,time travel,True,NaN,NaN,False,False,False,False,True,True,NaN
121175,twist ending,6600,386,2088,54,0.008182,0.017925,5.019010,narrative_structure,twist ending,True,NaN,NaN,False,False,False,False,True,True,NaN
84319,plot twist,2396,280,1031,51,0.021285,0.013003,5.339080,narrative_structure,plot twist,True,NaN,NaN,False,False,False,False,True,True,NaN
77090,nonlinear timeline,399,228,154,213,0.533835,0.010588,5.543713,narrative_structure,nonlinear,True,NaN,NaN,False,False,False,False,True,True,NaN
8816,bad ending,530,214,311,23,0.043396,0.009938,5.606797,narrative_structure,ending,True,NaN,NaN,False,False,False,False,True,True,NaN
35625,ending,470,198,258,26,0.055319,0.009195,5.684130,narrative_structure,ending,True,NaN,NaN,False,False,False,False,True,True,NaN
74968,narrated,757,191,331,79,0.104359,0.008870,5.719939,narrative_structure,narrated,True,NaN,NaN,False,False,False,False,True,True,NaN
49782,happy ending,685,186,366,33,0.048175,0.008638,5.746326,narrative_structure,ending,True,NaN,NaN,False,False,False,False,True,True,NaN
71355,mindfuck,3457,178,1385,51,0.014753,0.008266,5.790049,narrative_structure,mindfuck,True,NaN,NaN,False,False,False,False,True,True,NaN
24552,confusing,680,178,399,14,0.020588,0.008266,5.790049,narrative_structure,confusing,True,NaN,NaN,False,False,False,False,True,True,NaN
121169,twist,661,153,388,17,0.025719,0.007105,5.940482,narrative_structure,twist,True,NaN,NaN,False,False,False,False,True,True,NaN
30227,dialogue driven,703,149,379,38,0.054054,0.006919,5.966800,narrative_structure,dialogue driven,True,NaN,NaN,False,False,False,False,True,True,NaN
74978,narration,167,133,59,80,0.479042,0.006176,6.079595,narrative_structure,narration,True,NaN,NaN,False,False,False,False,True,True,NaN
77086,nonlinear,2097,129,1069,29,0.013829,0.005991,6.109900,narrative_structure,nonlinear,True,NaN,NaN,False,False,False,False,True,True,NaN
73759,multiple storylines,1514,129,804,49,0.032365,0.005991,6.109900,narrative_structure,multiple storylines,True,NaN,NaN,False,False,False,False,True,True,NaN
100079,sad ending,280,128,183,12,0.042857,0.005944,6.117622,narrative_structure,ending,True,NaN,NaN,False,False,False,False,True,True,NaN
4202,ambiguous ending,242,123,125,89,0.367769,0.005712,6.157153,narrative_structure,ambiguous ending,True,NaN,NaN,False,False,False,False,True,True,NaN
73920,murder mystery,477,116,309,47,0.098532,0.005387,6.215261,narrative_structure,mystery,True,NaN,NaN,False,False,False,False,True,True,NaN
19374,cerebral,827,101,444,38,0.045949,0.004690,6.352462,narrative_structure,cerebral,True,NaN,NaN,False,False,False,False,True,True,NaN

Top 20 tags finales por categoria: theme

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
23905,coming of age,4494,1029,1133,439,0.097686,0.047785,4.040121,theme,coming of age,True,NaN,NaN,False,False,False,False,True,True,NaN
39297,father daughter relationship,1517,974,287,767,0.505603,0.045231,4.094997,theme,father,True,NaN,NaN,False,False,False,False,True,True,NaN
38823,family relationships,1305,925,245,702,0.537931,0.042955,4.146561,theme,family relationships,True,NaN,NaN,False,False,False,False,True,True,NaN
85006,politics,2416,836,718,427,0.176738,0.038822,4.247611,theme,politics,True,NaN,NaN,False,False,False,False,True,True,NaN
96494,religion,2163,776,651,346,0.159963,0.036036,4.321994,theme,religion,True,NaN,NaN,False,False,False,False,True,True,NaN
108136,social commentary,5201,692,1529,160,0.030763,0.032135,4.436405,theme,social commentary,True,NaN,NaN,False,False,False,False,True,True,NaN
70118,mental illness,2698,578,942,208,0.077094,0.026841,4.616132,theme,mental illness,True,NaN,NaN,False,False,False,False,True,True,NaN
88807,racism,1718,576,577,303,0.176368,0.026748,4.619593,theme,racism,True,NaN,NaN,False,False,False,False,True,True,NaN
3526,alien,992,488,229,455,0.458669,0.022662,4.785072,theme,alien,True,NaN,NaN,False,False,False,False,True,True,NaN
78241,obsession,946,468,329,339,0.358351,0.021733,4.826832,theme,obsession,True,NaN,NaN,False,False,False,False,True,True,NaN
33985,dystopia,5713,441,1568,338,0.059163,0.020479,4.886125,theme,dystopia,True,NaN,NaN,False,False,False,False,True,True,NaN
90299,redemption,814,416,289,250,0.307125,0.019318,4.944349,theme,redemption,True,NaN,NaN,False,False,False,False,True,True,NaN
64820,loneliness,1635,399,688,249,0.152294,0.018529,4.985970,theme,loneliness,True,NaN,NaN,False,False,False,False,True,True,NaN
3668,aliens,3642,391,976,141,0.038715,0.018157,5.006173,theme,aliens,True,NaN,NaN,False,False,False,False,True,True,NaN
69963,memory,1031,386,402,340,0.329777,0.017925,5.019010,theme,memory,True,NaN,NaN,False,False,False,False,True,True,NaN
48322,grief,552,354,162,213,0.385870,0.016439,5.105317,theme,grief,True,NaN,NaN,False,False,False,False,True,True,NaN
87535,psychological,4081,353,1483,52,0.012742,0.016393,5.108138,theme,psychological,True,NaN,NaN,False,False,False,False,True,True,NaN
39410,father-son relationship,1218,348,458,64,0.052545,0.016160,5.122363,theme,father,True,NaN,NaN,False,False,False,False,True,True,NaN
87569,psychology,4847,326,1675,65,0.013410,0.015139,5.187475,theme,psychology,True,NaN,NaN,False,False,False,False,True,True,NaN
109097,space,3971,306,1376,127,0.031982,0.014210,5.250587,theme,space,True,NaN,NaN,False,False,False,False,True,True,NaN

Top 20 tags finales por categoria: humor

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
100840,satire,3573,764,1229,450,0.125945,0.035479,4.337559,humor,satire,True,NaN,NaN,False,False,False,False,True,True,NaN
27909,dark comedy,6153,742,1958,386,0.062734,0.034457,4.366739,humor,dark comedy,True,NaN,NaN,False,False,False,False,True,True,NaN
12519,black comedy,4071,739,1345,475,0.116679,0.034318,4.370785,humor,black comedy,True,NaN,NaN,False,False,False,False,True,True,NaN
88467,quirky,4954,515,1459,141,0.028462,0.023916,4.731328,humor,quirky,True,NaN,NaN,False,False,False,False,True,True,NaN
81304,parody,2006,407,723,177,0.088235,0.018900,4.966168,humor,parody,True,NaN,NaN,False,False,False,False,True,True,NaN
127845,witty,2144,335,918,67,0.031250,0.015557,5.160324,humor,witty,True,NaN,NaN,False,False,False,False,True,True,NaN
109939,spoof,625,277,212,212,0.339200,0.012863,5.349814,humor,spoof,True,NaN,NaN,False,False,False,False,True,True,NaN
106986,slapstick,516,221,222,76,0.147287,0.010263,5.574757,humor,slapstick,True,NaN,NaN,False,False,False,False,True,True,NaN
1555,absurd,895,207,501,19,0.021229,0.009613,5.639897,humor,absurd,True,NaN,NaN,False,False,False,False,True,True,NaN
100849,satirical,1160,188,573,95,0.081897,0.008730,5.735688,humor,satirical,True,NaN,NaN,False,False,False,False,True,True,NaN
101948,screwball comedy,331,102,135,69,0.208459,0.004737,6.342706,humor,screwball,True,NaN,NaN,False,False,False,False,True,True,NaN
28604,deadpan,402,87,222,54,0.134328,0.004040,6.500098,humor,deadpan,True,NaN,NaN,False,False,False,False,True,True,NaN
108217,social satire,287,84,174,63,0.219512,0.003901,6.534784,humor,satire,True,NaN,NaN,False,False,False,False,True,True,NaN
56969,irony,110,84,46,60,0.545455,0.003901,6.534784,humor,irony,True,NaN,NaN,False,False,False,False,True,True,NaN
56961,ironic,141,47,99,11,0.078014,0.002183,7.106234,humor,ironic,True,NaN,NaN,False,False,False,False,True,True,NaN
101947,screwball,99,39,58,10,0.101010,0.001811,7.288555,humor,screwball,True,NaN,NaN,False,False,False,False,True,True,NaN
33530,dry humor,55,32,41,10,0.181818,0.001486,7.480927,humor,dry humor,True,NaN,NaN,False,False,False,False,True,True,NaN
78430,offbeat,46,26,35,5,0.108696,0.001207,7.681598,humor,offbeat,True,NaN,NaN,False,False,False,False,True,True,NaN
127848,witty dialogue,84,22,76,4,0.047619,0.001022,7.841941,humor,witty,True,NaN,NaN,False,False,False,False,True,True,NaN
88476,quirky humor,32,14,29,3,0.093750,0.000650,8.269385,humor,quirky,True,NaN,NaN,False,False,False,False,True,True,NaN

Top 20 tags finales por categoria: visual_style

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
113611,surrealism,1752,774,602,707,0.403539,0.035943,4.324572,visual_style,surrealism,True,NaN,NaN,False,False,False,False,True,True,NaN
21945,cinematography,5429,757,1513,85,0.015657,0.035154,4.346751,visual_style,cinematography,True,NaN,NaN,False,False,False,False,True,True,NaN
113594,surreal,7480,688,2080,84,0.011230,0.031949,4.442194,visual_style,surreal,True,NaN,NaN,False,False,False,False,True,True,NaN
12455,black and white,1940,554,605,112,0.057732,0.025727,4.658467,visual_style,black and white,True,NaN,NaN,False,False,False,False,True,True,NaN
112643,stylized,4948,485,1370,200,0.040420,0.022523,4.791226,visual_style,stylized,True,NaN,NaN,False,False,False,False,True,True,NaN
124585,visually appealing,7253,481,2092,54,0.007445,0.022337,4.799491,visual_style,visually,True,NaN,NaN,False,False,False,False,True,True,NaN
75648,neo-noir,1243,258,507,169,0.135961,0.011981,5.420607,visual_style,neo-noir,True,NaN,NaN,False,False,False,False,True,True,NaN
32921,dreamlike,2759,225,1071,58,0.021022,0.010449,5.556900,visual_style,dreamlike,True,NaN,NaN,False,False,False,False,True,True,NaN
83131,photography,531,205,278,102,0.192090,0.009520,5.649559,visual_style,photography,True,NaN,NaN,False,False,False,False,True,True,NaN
124608,visually stunning,2059,191,1000,23,0.011170,0.008870,5.719939,visual_style,visually,True,NaN,NaN,False,False,False,False,True,True,NaN
37425,experimental,350,175,165,101,0.288571,0.008127,5.806951,visual_style,experimental,True,NaN,NaN,False,False,False,False,True,True,NaN
111726,stop motion,564,158,263,90,0.159574,0.007337,5.908531,visual_style,stop motion,True,NaN,NaN,False,False,False,False,True,True,NaN
112647,stylized violence,307,145,132,124,0.403909,0.006734,5.993828,visual_style,stylized,True,NaN,NaN,False,False,False,False,True,True,NaN
23629,colorful,511,96,307,15,0.029354,0.004458,6.402724,visual_style,colorful,True,NaN,NaN,False,False,False,False,True,True,NaN
107387,slow motion,127,72,62,41,0.322835,0.003344,6.686975,visual_style,slow motion,True,NaN,NaN,False,False,False,False,True,True,NaN
85988,practical effects,228,69,153,14,0.061404,0.003204,6.728940,visual_style,practical effects,True,NaN,NaN,False,False,False,False,True,True,NaN
47916,great cinematography,564,67,379,6,0.010638,0.003111,6.757927,visual_style,cinematography,True,NaN,NaN,False,False,False,False,True,True,NaN
124606,visually striking,237,59,149,42,0.177215,0.002740,6.883090,visual_style,visually,True,NaN,NaN,False,False,False,False,True,True,NaN
10572,beautiful cinematography,316,50,237,9,0.028481,0.002322,7.045609,visual_style,cinematography,True,NaN,NaN,False,False,False,False,True,True,NaN
104491,shaky camera,220,50,147,12,0.054545,0.002322,7.045609,visual_style,shaky camera,True,NaN,NaN,False,False,False,False,True,True,NaN

Top 20 tags finales por categoria: tone_atmosphere

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
7469,atmospheric,10088,817,2205,213,0.021114,0.037940,4.270572,tone_atmosphere,atmospheric,True,NaN,NaN,False,False,False,False,True,True,NaN
27896,dark,4825,522,1527,56,0.011606,0.024241,4.717853,tone_atmosphere,dark,True,NaN,NaN,False,False,False,False,True,True,NaN
31619,disturbing,4053,430,1343,116,0.028621,0.019968,4.911327,tone_atmosphere,disturbing,True,NaN,NaN,False,False,False,False,True,True,NaN
115943,tense,2643,415,948,185,0.069996,0.019272,4.946750,tone_atmosphere,tense,True,NaN,NaN,False,False,False,False,True,True,NaN
100069,sad,885,323,465,24,0.027119,0.015000,5.196691,tone_atmosphere,sad,True,NaN,NaN,False,False,False,False,True,True,NaN
126432,weird,1571,313,714,26,0.016550,0.014535,5.228042,tone_atmosphere,weird,True,NaN,NaN,False,False,False,False,True,True,NaN
50157,haunting,330,281,65,154,0.466667,0.013049,5.335528,tone_atmosphere,haunting,True,NaN,NaN,False,False,False,False,True,True,NaN
12411,bittersweet,2757,270,1065,66,0.023939,0.012538,5.375316,tone_atmosphere,bittersweet,True,NaN,NaN,False,False,False,False,True,True,NaN
26172,creepy,1417,265,623,49,0.034580,0.012306,5.393938,tone_atmosphere,creepy,True,NaN,NaN,False,False,False,False,True,True,NaN
29724,depressing,1218,247,661,15,0.012315,0.011470,5.464006,tone_atmosphere,depressing,True,NaN,NaN,False,False,False,False,True,True,NaN
48384,gritty,1121,231,472,69,0.061552,0.010727,5.530697,tone_atmosphere,gritty,True,NaN,NaN,False,False,False,False,True,True,NaN
50548,heartwarming,1507,222,727,29,0.019244,0.010309,5.570263,tone_atmosphere,heartwarming,True,NaN,NaN,False,False,False,False,True,True,NaN
39696,feel-good,1244,210,689,17,0.013666,0.009752,5.625577,tone_atmosphere,feel-good,True,NaN,NaN,False,False,False,False,True,True,NaN
27933,dark humor,1735,188,894,29,0.016715,0.008730,5.735688,tone_atmosphere,dark,True,NaN,NaN,False,False,False,False,True,True,NaN
12886,bleak,566,180,250,98,0.173145,0.008359,5.778938,tone_atmosphere,bleak,True,NaN,NaN,False,False,False,False,True,True,NaN
52752,hope,334,173,156,136,0.407186,0.008034,5.818379,tone_atmosphere,hope,True,NaN,NaN,False,False,False,False,True,True,NaN
69863,melancholy,798,155,425,54,0.067669,0.007198,5.927579,tone_atmosphere,melancholy,True,NaN,NaN,False,False,False,False,True,True,NaN
77282,nostalgic,531,155,311,29,0.054614,0.007198,5.927579,tone_atmosphere,nostalgic,True,NaN,NaN,False,False,False,False,True,True,NaN
115950,tension,424,139,251,90,0.212264,0.006455,6.035792,tone_atmosphere,tension,True,NaN,NaN,False,False,False,False,True,True,NaN
1565,absurdism,232,133,98,116,0.500000,0.006176,6.079595,tone_atmosphere,absurdism,True,NaN,NaN,False,False,False,False,True,True,NaN

Top 20 tags finales por categoria: emotional_cognitive_experience

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
117306,thought-provoking,6003,360,2035,65,0.010828,0.016718,5.088557,emotional_cognitive_experience,thought-provoking,True,NaN,NaN,False,False,False,False,True,True,NaN
35383,emotional,2289,346,965,44,0.019222,0.016068,5.128110,emotional_cognitive_experience,emotional,True,NaN,NaN,False,False,False,False,True,True,NaN
56297,intense,1759,229,854,24,0.013644,0.010634,5.539355,emotional_cognitive_experience,intense,True,NaN,NaN,False,False,False,False,True,True,NaN
73459,moving,265,134,168,41,0.154717,0.006223,6.072160,emotional_cognitive_experience,moving,True,NaN,NaN,False,False,False,False,True,True,NaN
117299,thought provoking,487,88,346,18,0.036961,0.004087,6.488798,emotional_cognitive_experience,thought provoking,True,NaN,NaN,False,False,False,False,True,True,NaN
56253,intellectual,676,77,506,18,0.026627,0.003576,6.620726,emotional_cognitive_experience,intellectual,True,NaN,NaN,False,False,False,False,True,True,NaN
24175,complex characters,436,63,316,23,0.052752,0.002926,6.818552,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN
24174,complex,341,51,247,9,0.026393,0.002368,7.026191,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN
122777,unsettling,192,50,144,13,0.067708,0.002322,7.045609,emotional_cognitive_experience,unsettling,True,NaN,NaN,False,False,False,False,True,True,NaN
85956,powerful,88,48,64,8,0.090909,0.002229,7.085614,emotional_cognitive_experience,powerful,True,NaN,NaN,False,False,False,False,True,True,NaN
71317,mind bending,267,35,219,5,0.018727,0.001625,7.393916,emotional_cognitive_experience,mind bending,True,NaN,NaN,False,False,False,False,True,True,NaN
4199,ambiguous,110,34,85,10,0.090909,0.001579,7.422087,emotional_cognitive_experience,ambiguous,True,NaN,NaN,False,False,False,False,True,True,NaN
24182,complex relationships,110,34,72,18,0.163636,0.001579,7.422087,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN
72717,morally complex,152,27,117,7,0.046053,0.001254,7.645230,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN
54917,immersive,188,23,145,8,0.042553,0.001068,7.799381,emotional_cognitive_experience,immersive,True,NaN,NaN,False,False,False,False,True,True,NaN
87353,provocative,88,21,78,5,0.056818,0.000975,7.886392,emotional_cognitive_experience,provocative,True,NaN,NaN,False,False,False,False,True,True,NaN
69945,memorable characters,52,21,32,10,0.192308,0.000975,7.886392,emotional_cognitive_experience,memorable,True,NaN,NaN,False,False,False,False,True,True,NaN
46774,god complex,42,18,28,13,0.309524,0.000836,8.032996,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN
71131,military industrial complex,29,18,13,10,0.344828,0.000836,8.032996,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN
78398,oedipus complex,18,17,10,7,0.388889,0.000789,8.087063,emotional_cognitive_experience,complex,True,NaN,NaN,False,False,False,False,True,True,NaN

Top 20 tags finales por categoria: intensity_darkness

,tag_clean,n_uses,n_movies,n_users,top_user_uses,top_user_share,pct_movies,idf,semantic_category,semantic_match_reason,preliminary_keep,hard_rejection_reason,semantic_rejection_reason,fail_low_n_movies,fail_low_n_users,fail_high_pct_movies,fail_high_top_user_share,passes_statistical_filters,is_reliable_tag,rejection_reason_statistical
103370,serial killer,2763,785,828,523,0.189287,0.036454,4.310478,intensity_darkness,serial killer,True,NaN,NaN,False,False,False,False,True,True,NaN
119601,tragedy,691,375,294,223,0.322721,0.017414,5.047846,intensity_darkness,tragedy,True,NaN,NaN,False,False,False,False,True,True,NaN
124352,violent,1555,243,644,33,0.021222,0.011284,5.480267,intensity_darkness,violent,True,NaN,NaN,False,False,False,False,True,True,NaN
101155,scary,523,157,295,15,0.028681,0.007291,5.914840,intensity_darkness,scary,True,NaN,NaN,False,False,False,False,True,True,NaN
32201,domestic violence,235,151,79,97,0.412766,0.007012,5.953554,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN
113771,suspenseful,982,126,542,12,0.012220,0.005851,6.133248,intensity_darkness,suspenseful,True,NaN,NaN,False,False,False,False,True,True,NaN
16059,brutal,648,125,367,36,0.055556,0.005805,6.141153,intensity_darkness,brutal,True,NaN,NaN,False,False,False,False,True,True,NaN
13233,bloody,323,92,208,24,0.074303,0.004272,6.444835,intensity_darkness,bloody,True,NaN,NaN,False,False,False,False,True,True,NaN
47771,graphic violence,196,92,112,72,0.367347,0.004272,6.444835,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN
47443,gory,216,83,154,9,0.041667,0.003854,6.546618,intensity_darkness,gory,True,NaN,NaN,False,False,False,False,True,True,NaN
119617,tragic hero,151,83,66,74,0.490066,0.003854,6.546618,intensity_darkness,tragic,True,NaN,NaN,False,False,False,False,True,True,NaN
104267,sexual violence,122,73,63,57,0.467213,0.003390,6.673370,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN
119606,tragic,144,60,117,5,0.034722,0.002786,6.866561,intensity_darkness,tragic,True,NaN,NaN,False,False,False,False,True,True,NaN
77560,not scary,81,49,57,6,0.074074,0.002275,7.065412,intensity_darkness,scary,True,NaN,NaN,False,False,False,False,True,True,NaN
104279,sexualized violence,223,43,136,29,0.130045,0.001997,7.193245,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN
16070,brutal violence,93,38,62,24,0.258065,0.001765,7.313873,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN
103379,serial killers,63,36,34,12,0.190476,0.001672,7.366517,intensity_darkness,serial killer,True,NaN,NaN,False,False,False,False,True,True,NaN
47805,gratuitous violence,201,31,157,4,0.019900,0.001440,7.511699,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN
74017,murder plot,34,27,10,20,0.588235,0.001254,7.645230,intensity_darkness,murder,True,NaN,NaN,False,False,False,False,True,True,NaN
23879,comic violence,47,23,27,20,0.425532,0.001068,7.799381,intensity_darkness,violence,True,NaN,NaN,False,False,False,False,True,True,NaN

Muestra aleatoria de 50 tags finales aceptados

                   tag_clean               semantic_category  n_movies  n_uses
1555                  absurd                           humor       207     895
2886                      ai                           theme        57     331
3590      alien intelligence                           theme         5      11
3594          alien invasion                           theme       182     854
5853           anti-religion                           theme         8      35
16059                 brutal              intensity_darkness       125     648
22253           class divide                           theme        11      41
22263          class society                           theme        23      31
22268           class themes                           theme        38     148
22417         claustrophobic                 tone_atmosphere       113     583
23908    coming of age story                           theme         9      17
24175     complex characters  emotional_cognitive_experience        63     436
24183         complex script  emotional_cognitive_experience        13      60
27899              dark ages                 tone_atmosphere        10      12
28643     dealing with death                           theme         8      10
31171   disappointing ending             narrative_structure        31      62
31185    disapproving father                           theme         7      10
32201      domestic violence              intensity_darkness       151     235
32905        dream sequences             narrative_structure         8       9
34204     eastern philosophy                           theme         5      16
34644                  eerie                 tone_atmosphere        86     357
39313          father figure                           theme        71     109
39696              feel-good                 tone_atmosphere       210    1244
40006      female friendship                           theme       125     207
47916   great cinematography                    visual_style        67     564
50548           heartwarming                 tone_atmosphere       222    1507
52843        horrible ending             narrative_structure         8      16
52920          horror parody                           humor         8      12
60882          killer robots                           theme         5      11
69963                 memory                           theme       386    1031
81304                 parody                           humor       407    2006
84319             plot twist             narrative_structure       280    2396
84967   political propaganda                           theme         6       8
84978       political satire                           theme        83     187
84979      political scandal                           theme         8      11
85700        post-apocalypse                           theme         9      36
88467                 quirky                           humor       515    4954
99208            rotoscoping                    visual_style        31      62
101156         scary as hell              intensity_darkness         9      14
112568         stupid ending             narrative_structure        44     147
115950               tension                 tone_atmosphere       139     424
119606                tragic              intensity_darkness        60     144
122733  unreliable narrators             narrative_structure        16      76
123012        urban violence              intensity_darkness         8      20
123817              very sad                 tone_atmosphere         5      10
124367        violent father                           theme         9      18
124606     visually striking                    visual_style        59     237
126432                 weird                 tone_atmosphere       313    1571
126450          weird ending             narrative_structure         8      12
129009           work ethics                           theme        22      25

Muestra aleatoria de 50 tags rechazados por semantic_category_missing

                                     tag_clean  n_movies  n_uses
2274          adult actress playing minor girl         7       7
3461               alfred pennyworth character         8       8
4374                        american in london         2       2
11895                            biker cap hat         1       1
19434                 ch 47 chinook helicopter         6       6
20274                         cheating on wife         8       8
20614   chick flick that guys would find funny         1       1
21353                               chop socky        22      23
24629                                     cons         2       2
31571                          distorted voice         6       6
33734                            dumdum bullet         1       1
38026                         facing the truth         1       1
46951                           golden earring         1       1
50553                     heat seeking missile         1       1
52590                       homosexual history         3       3
53167                                hot pants        12      12
62862                             leather cops         1       2
64188                        lisboa california         1       1
69015                                  masseur        13      14
69353                     may-december romance        37      66
71951                       mitsubishi eclipse         2       2
73092                  motion picture industry         4       4
75782                                   nevada        41      47
77892                        nude teenage girl         1       1
86664                                 printing         4       4
86685                               prisioners         1       1
88234                                   q bert         1       1
89781                         realisitc acting         1      19
90327                 redondo beach california         1       1
92629         reference to henry david thoreau         5       5
93170                 reference to jules verne         3       3
96520                   religious conservative         1       1
97267                             retro future         7       9
100437                                 sambola         1       1
100668                   santa claus character        10      10
104353                             sexy sister         1       1
104379                                  shabby         5       5
104441                            shakespearan         2       2
109675                                   spies        58     376
109929                             spontaneous         1       1
111870                  straight razor shaving         1       2
112302                              struggling         2       2
114831                                   talon         1       1
115320                      tearing up a diary         1       1
115865                          temper tantrum         9       9
116617                    the leader character         1       1
116820                                 the sun         2       2
117040                                theorist         1       1
120901                     turned into a human         1       1
126289                            weather vane         4       4

Muestra aleatoria de 50 tags rechazados por person_name_like

                       tag_clean  n_movies  n_uses
13613                bobby mauch         1       1
15270               brent sexton         1       1
15387           brief encounters        12      16
15674               broken blade         6       6
20084      charlie kaufman-esque         1       2
21449              chris pontias         1       1
25914              craig roberts         1       2
27169                cutting ear         1       1
27592     dana wheeler-nicholson         1       1
30168             devon gearhart         1       1
31038    director: steve mcqueen         1       1
31057       director: tim miller         1       1
32567                 doug liman         4      11
34548                 edie falco         1       1
35143            ellen lancaster         1       1
36524        ethan hawke (cameo)         1       1
46194           ginnifer goodwin         3       3
49715                hank azaria        11      28
57340               ivor novello         2       3
57613                jake thomas         1       1
57727              james spinney         1       1
58823              joe charbanic         1       1
59209             jonathan louis         1       1
59498               julia dietze         1       7
61548                 ko ah-sung         1       3
63457                lewis stone         1       1
64521             lloydd bridges         1       3
65853               lucy russell         1       2
66657                 maka kotto         1       1
68023                mana ashida         1       2
68344            margarete schon         1       1
69236              matthew maher         1       2
69302               max cavalera         1       1
70752            michael winslow         5      12
71004                  mike suby         1       1
80565          pacific islanders         1       1
82132             penny marshall         2       3
83402              pierre arditi         2       2
98232                rob corddry         2       3
100502           samurai fiction         1       1
100791                sasha luss         1       3
101548      scientist love story         1       2
108038                   so long         1       2
114627            talking babies         2       5
117975             tim mcinnerny         2       2
118609             tom schilling         3       5
126619                wes craven        13      66
126621                 wes studi         3       4
127671              winona ryder        25     225
130107  writer: terence rattigan         2       2

Comprobacion de tags problematicos

                 tag_clean  present_in_tags_semantic_clean
0   national film registry                           False
1                    pixar                           False
2                   disney                           False
3                brilliant                           False
4                  foreign                           False
5    based on a true story                           False
6                    1980s                           False
7                    1990s                           False
8    nudity (full frontal)                           False
9              dave franco                           False
10             isla fisher                           False
11       christopher nolan                           False
12           coen brothers                           False
13               tom hanks                           False
14             hans zimmer                           False
15            great acting                           False
16               cult film                           False
17                   owned                           False
18            imdb top 250                           False
19                   oscar                           False
20               criterion                           False
21                     dvd                           False
22                 netflix                           False

Comprobacion de tags utiles

            tag_clean  exists_in_tags_csv  present_in_tags_semantic_clean
0          surrealism                True                            True
1           dreamlike                True                            True
2      existentialism                True                            True
3       psychological                True                            True
4    ambiguous ending                True                            True
5            neo-noir                True                            True
6         atmospheric                True                            True
7         time travel                True                            True
8   thought-provoking                True                            True
9         dark comedy                True                            True
10       black comedy                True                            True
11  social commentary                True                            True
12         plot twist                True                            True
13       twist ending                True                            True
14           mindfuck                True                            True
15        bittersweet                True                            True
16             quirky                True                            True
17          satirical                True                            True
18           cerebral                True                            True
19    magical realism                True                            True
20              tense                True                            True
21           morality                True                            True

In [22]:
# ============================================================
# Export diagnóstico resumido del preprocesado semántico de tags
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

DIAG_DIR = REPORTS_RESULTADOS
DIAG_DIR.mkdir(parents=True, exist_ok=True)

diagnostic_rows = []

def add_metric(section, metric, value):
    diagnostic_rows.append({
        "section": section,
        "metric": metric,
        "value": value
    })

# -----------------------------
# 1. Resumen general
# -----------------------------
try:
    add_metric("summary", "raw_rows", len(tags_raw))
    add_metric("summary", "raw_unique_tags", tags_raw["tag"].nunique(dropna=True))
except Exception as e:
    add_metric("summary", "raw_error", str(e))

try:
    add_metric("summary", "tag_clean_valid_rows", tags_work["tag_clean"].notna().sum())
    add_metric("summary", "semantic_category_rows", tags_work["semantic_category"].notna().sum())
    add_metric("summary", "semantic_category_missing_rows", tags_work["semantic_category"].isna().sum())
except Exception as e:
    add_metric("summary", "tags_work_error", str(e))

try:
    add_metric("summary", "final_reliable_tags", tag_stats["is_reliable_tag"].sum())
    add_metric("summary", "final_unique_tags_clean", tags_semantic_clean["tag_clean"].nunique())
    add_metric("summary", "final_rows_tags_semantic_clean", len(tags_semantic_clean))
    add_metric("summary", "final_movies_with_semantic_tags", tags_semantic_clean["movieId"].nunique())
except Exception as e:
    add_metric("summary", "final_error", str(e))

# -----------------------------
# 2. Distribución categorías
# -----------------------------
try:
    cat_unique = (
        tag_stats[tag_stats["is_reliable_tag"]]
        .groupby("semantic_category")["tag_clean"]
        .nunique()
        .reset_index(name="n_unique_tags")
        .sort_values("n_unique_tags", ascending=False)
    )
    cat_unique.to_csv(
        DIAG_DIR / "diagnostico_09_semantic_category_unique_tags.csv",
        index=False,
        encoding="utf-8-sig"
    )

    cat_rows = (
        tags_semantic_clean
        .groupby("semantic_category")
        .size()
        .reset_index(name="n_rows")
        .sort_values("n_rows", ascending=False)
    )
    cat_rows.to_csv(
        DIAG_DIR / "diagnostico_09_semantic_category_rows.csv",
        index=False,
        encoding="utf-8-sig"
    )
except Exception as e:
    add_metric("semantic_category", "error", str(e))

# -----------------------------
# 3. Top tags finales por categoría
# -----------------------------
try:
    top_tags_by_category = (
        tag_stats[tag_stats["is_reliable_tag"]]
        .sort_values(["semantic_category", "n_movies", "n_uses"], ascending=[True, False, False])
        .groupby("semantic_category")
        .head(20)
        .loc[:, [
            "semantic_category",
            "tag_clean",
            "n_uses",
            "n_movies",
            "n_users",
            "top_user_share",
            "pct_movies",
            "idf"
        ]]
    )

    top_tags_by_category.to_csv(
        DIAG_DIR / "diagnostico_09_top_tags_by_category.csv",
        index=False,
        encoding="utf-8-sig"
    )
except Exception as e:
    add_metric("top_tags_by_category", "error", str(e))

# -----------------------------
# 4. Comprobación tags problemáticos y útiles
# -----------------------------
problematic_tags = [
    "national film registry",
    "pixar",
    "disney",
    "brilliant",
    "foreign",
    "based on a true story",
    "1980s",
    "nudity (full frontal)",
    "dave franco",
    "isla fisher",
    "christopher nolan",
    "coen brothers",
    "tom hanks",
    "hans zimmer",
    "great acting",
    "cult film",
    "owned",
    "imdb top 250",
    "oscar",
    "criterion",
    "dvd",
    "netflix",
]

useful_tags = [
    "surrealism",
    "dreamlike",
    "existentialism",
    "psychological",
    "ambiguous ending",
    "neo-noir",
    "atmospheric",
    "time travel",
    "thought-provoking",
    "dark comedy",
    "black comedy",
    "social commentary",
    "plot twist",
    "twist ending",
    "mindfuck",
    "bittersweet",
    "quirky",
    "satirical",
    "cerebral",
    "magical realism",
    "tense",
    "morality",
]

try:
    final_tag_set = set(tags_semantic_clean["tag_clean"].dropna().astype(str))

    tag_checks = []
    for tag in problematic_tags:
        tag_checks.append({
            "type": "problematic",
            "tag_clean": tag,
            "present_in_tags_semantic_clean": tag in final_tag_set
        })

    for tag in useful_tags:
        tag_checks.append({
            "type": "useful",
            "tag_clean": tag,
            "present_in_tags_semantic_clean": tag in final_tag_set
        })

    tag_checks_df = pd.DataFrame(tag_checks)
    tag_checks_df.to_csv(
        DIAG_DIR / "diagnostico_09_tag_checks.csv",
        index=False,
        encoding="utf-8-sig"
    )
except Exception as e:
    add_metric("tag_checks", "error", str(e))

# -----------------------------
# 5. Rechazos principales
# -----------------------------
try:
    if "hard_rejection_reason" in tags_work.columns:
        hard_rejections = (
            tags_work["hard_rejection_reason"]
            .value_counts(dropna=False)
            .reset_index()
        )
        hard_rejections.columns = ["hard_rejection_reason", "count"]
        hard_rejections.to_csv(
            DIAG_DIR / "diagnostico_09_hard_rejections.csv",
            index=False,
            encoding="utf-8-sig"
        )
except Exception as e:
    add_metric("hard_rejections", "error", str(e))

# -----------------------------
# 6. Guardar resumen
# -----------------------------
diagnostico_09_summary = pd.DataFrame(diagnostic_rows)
diagnostico_09_summary.to_csv(
    DIAG_DIR / "diagnostico_09_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Diagnóstico 09 exportado en:")
print(DIAG_DIR / "diagnostico_09_summary.csv")
print(DIAG_DIR / "diagnostico_09_semantic_category_unique_tags.csv")
print(DIAG_DIR / "diagnostico_09_semantic_category_rows.csv")
print(DIAG_DIR / "diagnostico_09_top_tags_by_category.csv")
print(DIAG_DIR / "diagnostico_09_tag_checks.csv")
print(DIAG_DIR / "diagnostico_09_hard_rejections.csv")

Diagnóstico 09 exportado en:
..\reports\resultados\diagnostico_09_summary.csv
..\reports\resultados\diagnostico_09_semantic_category_unique_tags.csv
..\reports\resultados\diagnostico_09_semantic_category_rows.csv
..\reports\resultados\diagnostico_09_top_tags_by_category.csv
..\reports\resultados\diagnostico_09_tag_checks.csv
..\reports\resultados\diagnostico_09_hard_rejections.csv

## 11. Criterios de aceptacion

Al ejecutarse completo, este notebook debe generar:

- `data/processed/tags_semantic_clean.csv`
- `data/processed/tag_semantic_stats.csv`
- `data/processed/tag_blacklist_detected.csv`
- `data/processed/tag_blacklist_manual.csv`

`tags_semantic_clean.csv` conserva las columnas base que usa el notebook 08 (`movieId`, `tag_clean`, `idf`) y anade `semantic_category` para auditoria. No usa APIs externas, LightFM, spaCy, sentence-transformers ni dependencias nuevas.